language: node_js
node_js:
- 10.3.0
install:
- npm install
script:
- gulp
- npm run webpackdev
- scp -r ./src root:/home/mengjing/github
before_install:
- openssl aes-256-cbc -K $encrypted_f6d3fa33a8a5_key -iv $encrypted_f6d3fa33a8a5_iv
  -in github-key.enc -out github-key -d
